project_id = "frcbjztdvufvenblnyqz"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
enabled = true
port = 54323

# Enable the Edge Functions API
[functions]
[functions.fetch-census-data]
verify_jwt = false