// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://frcbjztdvufvenblnyqz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZyY2JqenRkdnVmdmVuYmxueXF6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzM4OTMxNzUsImV4cCI6MjA0OTQ2OTE3NX0.7ApSiJHpE-YsVlPCHwv0sxDoPEZkbHn0TJSIe1kwQAQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);